version: "3.9"

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  mongo:
    <<: *restart_policy
    image: mongo:5.0.9
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-mongo_u}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-mongo_p}
      - MONGO_INITDB_DATABASE=${DB_DBNAME:-mongo_db}
    volumes:
      - ./db-data:/data/db
    ports:
      - 27017:27017

  mongo-express:
    <<: *restart_policy
    image: mongo-express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME:-mongo_u}:${DB_PASSWORD:-mongo_p}@mongo:27017/
    ports:
      - 8081:8081
